### ISSUE TITLE
Wiki from Restbot-API make 404

### ISSUE THREAD

**Issue by gsegit** [GwynethLlewelyn/restbot#10]
Hi there ;D
The Wiki from Restbot-API make a 404 - Site not found, can you fix this ;D

Greetings

Bogus (Germany)

**Comment by iDJHost** [comment]
Reproduced:

Link found at https://github.com/GwynethLlewelyn/restbot/wiki 
Linked text: "RESTbot API" resolves to:
https://github.com/GwynethLlewelyn/restbot/RESTbot-API (missing /wiki)

Instead of the proper url:
https://github.com/GwynethLlewelyn/restbot/wiki/RESTbot-API

**Comment by GwynethLlewelyn** [comment]
Ah! Thanks so much, @iDJHost! Both you and @gsegit are correct. My problem was that I don't place full paths on the Wiki, just relative ones, so that GitHub automatically fills them in (if they move them, or if someone forks the Wiki, relative paths should continue to work); as such, it was hard for me to figure out what was wrong with the Markdown!

Well, it was easy enough to fix... I had an extraneous "`../`" which 'deleted' the `wiki` part of the URL :) Removing that fixed the Wiki link for me; hopefully it fixes for you two as well.

Thanks for reporting!
